project:
  type: website

website:
  title: "quarto_gestao_report"
  favicon: 'files/ipea_logo.png'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



